# ===========================================================================
# Project:   Flot-integration
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :lot, :required => [:sproutcore]
config :demo, :required => [:sproutcore, 'flot']